sudo: required
services:
- docker
env:
  global:
    - POSTGRES_URI="user=pguser password=pguser dbname=api-melvin host=ml_api_postgres sslmode=disable"
    - secure: "CP5hpihwZsv60Dcn6N2+TiP9CMpTaNX0tMM9AudsRLt50QPsZkcAVDiMhsegW+vfAAkM4cw4IvdKqgkv/9JYt+HCAd3pErTzh+MRLxr5HkagfV8aZfeU/fLrXAo9vGpnc/v23tbWoPRh8pWyOJ78gnxsPZHgKRsNNSJ2AYW5ApU="
install:
- cp config/api-common.env config/api.env
- cp config/database-common.env config/database.env
- docker-compose build
- docker-compose up -d
script:
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api
  && make migration"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && go test ./..."
deploy:
  - provider: script
    on: staging
    skip_cleanup: true
    script: ./deploy_staging.sh
notifications:
  email:
    recipients:
      secure: OalMK7QSZmKRoGckdxnc71XoB8hSw2kzncuAsBkaa3tMGNsBUP/NRTNAOTVu7krXdyh9kze+nlxULnLAkK82OaBkLEbsTecZ7jixwgRt/A2TXswxWxFdMUw+z6xVi7tieyXETQsUpjCrhweV+pdZxlvN0RAvg9yHluX/vq9u/ScH1qqWT4v/L6oDRnPD2FBPQIl4hr12nFCupcDjNIm8Lx6UfXANOmjSlXl5GGE5LxqjRinkbeYNIRhjFctjHUH6s9g4WlM0+/9iM/d3reCWs7emYzVvxZHIVf8GmbDXXhv425wPS97C5cpwo0MHxh3EAAbCFVkLPD3LYivULR4ZGFn0F/GzGP51F19bSeDwwFTRjD3hf5FCZ7nLXAKbuqQuvGbz8DMxw+xhwBTElRfph88K0MAqAlvjh8s919FnYJ93iDvyVSPcvoSV8+ilBxB5oejGxb2cIBigIIXNVr6FaSI5IkFDzCWfnwlD/qjUYmR1N0qYKca5xK7VpLU2VcERH/kMQSFCQFOVqkxmxF+/YPAkK0myYonPspKy5F+2t7aywdhv0jA79/ezUHKeK1MkmPmxjmNZFIESR0zKHGGh8eTYZPG/wp2TahxIGk6fMNQ7R6+cUqskgt5r/CPBl3SDAHMMlZuiuDvxlXKVSNuISPw/OZ41qi39tksQtNho+Sk=
    on_success: change
    on_failure: always
