sudo: required
services:
- docker
env:
  global:
    - POSTGRES_URI="user=pguser password=pguser dbname=api-melvin host=ml_api_postgres sslmode=disable"
    - secure: "CP5hpihwZsv60Dcn6N2+TiP9CMpTaNX0tMM9AudsRLt50QPsZkcAVDiMhsegW+vfAAkM4cw4IvdKqgkv/9JYt+HCAd3pErTzh+MRLxr5HkagfV8aZfeU/fLrXAo9vGpnc/v23tbWoPRh8pWyOJ78gnxsPZHgKRsNNSJ2AYW5ApU="
install:
- cp config/api-common.env config/api.env
- cp config/database-common.env config/database.env
- docker-compose build
- docker-compose up -d
script:
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api
  && make migration"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && go test -tags=integration  ./..."
deploy:
  - provider: script
    on: staging
    skip_cleanup: true
    script: ./deploy_staging.sh
notifications:
  email:
    recipients:
      secure: "fjpT9Utz25ML9Z6ShtwSm3rn8aRBh7TiMEAFplTGqMJAglWb05tPrUA0186nim4K1fNUgVedVEqnhPF/htZsq88T3d1Hq3Fm9xI4vpA53O/p8mZTOr2iweqKei+YSsxddNTYs/+EoYTNViuRR3sb/M/BhWOlAwIgqeiLo8kNpe0="
    on_success: change
    on_failure: always
