sudo: required

services:
  - docker

env:
  - ML_BUILD_ENV=test

install:
  - docker-compose build
  - docker-compose up -d
  - docker exec -i -t ml_api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api && make migration"

script:
  - docker exec -i -t ml_api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src && go test ./..."