sudo: required

services:
  - docker

env:
  - ML_BUILD_ENV=test

install:
  - docker-compose build
  - docker-compose up -d

script:
  - docker exec -i -t ml_api /bin/bash -ic "cd /go/src/github.com/Nivl/api.melvin.la/ && make migration"
  - docker exec -i -t ml_api /bin/bash -ic "cd /go/src/github.com/Nivl/api.melvin.la/api && go test ./..."