sudo: required
services:
- docker
env:
  global:
    - POSTGRES_URI="user=pguser password=pguser dbname=api-melvin host=ml_api_postgres sslmode=disable"
    - secure: "oCmYUNpZaUApnjMOdtZpfef0iIinEkCPGh8Ywj621SC01VuFewnwwnaV9jsN5B0XoN1DQcNXExmeHvqEjAMu45phB+1YAh+W70maXGtAM4SAFTQrb7Or+cJiJlfRR8uxg5urhbx449BvlOo0dMrWdDd+b72S1fHpmM6So9g3zm0="
    - secure: "cSZSr+yJpzezK/DxuveGjfGDEORSksZ/D1z9lHWGu/MFsOK39UrYwDaiGfjqph3EWpdytWIE7TKqmHwpMUFq2rLEn1ujicSFSLwZ+aEUKLq2UvktabVu1b1UAALlwJBkUPYdR7cuaqBiHLvRSbXZTWeZY6RS9yTTwkaW7rrWQgA="
before_install:
- gem install apiaryio
- npm install -g hercule
install:
- cp config/api-common.env config/api.env
- cp config/database-common.env config/database.env
- docker-compose build
- docker-compose up -d
script:
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api
  && make migration"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && ../go.test.sh"
after_success:
- hercule doc/main.apib -o apiary.apib && apiary publish --api-name="apimelvinla"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && CODECOV_ENV=$CODECOV_ENV CODECOV_TOKEN=$CODECOV_TOKEN CODECOV_URL=$CODECOV_URL CODECOV_SLUG=$CODECOV_SLUG VCS_COMMIT_ID=$VCS_COMMIT_ID VCS_BRANCH_NAME=$VCS_BRANCH_NAME VCS_PULL_REQUEST=$VCS_PULL_REQUEST VCS_SLUG=$VCS_SLUG VCS_TAG=$VCS_TAG CI_BUILD_URL=$CI_BUILD_URL CI_BUILD_ID=$CI_BUILD_ID CI_JOB_ID=$CI_JOB_ID CI=$CI TRAVIS=$TRAVIS SHIPPABLE=$SHIPPABLE TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_COMMIT=$TRAVIS_COMMIT TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_JOB_ID=$TRAVIS_JOB_ID TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG TRAVIS_TAG=$TRAVIS_TAG TRAVIS_OS_NAME=$TRAVIS_OS_NAME include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)"
deploy:
  - provider: script
    on: staging
    skip_cleanup: true
    script: ./deploy_staging.sh
notifications:
  email:
    recipients:
      secure: "fjpT9Utz25ML9Z6ShtwSm3rn8aRBh7TiMEAFplTGqMJAglWb05tPrUA0186nim4K1fNUgVedVEqnhPF/htZsq88T3d1Hq3Fm9xI4vpA53O/p8mZTOr2iweqKei+YSsxddNTYs/+EoYTNViuRR3sb/M/BhWOlAwIgqeiLo8kNpe0="
    on_success: change
    on_failure: always
