sudo: required
services:
- docker
env:
- ML_BUILD_ENV=test POSTGRES_URI="user=pguser password=pguser dbname=api-melvin host=ml_api_postgres
  sslmode=disable"
install:
- docker-compose build
- docker-compose up -d
script:
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api
  && make migration"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && go test ./..."
deploy:
  - provider: heroku
      app: melvin-laplanche
      api_key:
        secure: aXn1Xk+NLD+nqh5OFEfqmPsMN8n3+Q23kUdITkRY5vkxI7qp7W6Ov6MR4szoiJMEFh8FY8bBPzNmnmrUi5kr9xHb83aG+0JQXA6RxoExQ6OYOhVUETtzIUWVWUHQ/ltnXUwhTFJmBj9dYWbyelpILV9D0Wqu8EU2K0MXYz2Yf6M=
      on: staging
      run: "cd /go/src/github.com/melvin-laplanche/ml-api && goose up"
      script: heroku container:push web