sudo: required
services:
- docker
env:
  global:
    - POSTGRES_URI="user=pguser password=pguser dbname=api-melvin host=ml_api_postgres sslmode=disable"
    - secure: "CP5hpihwZsv60Dcn6N2+TiP9CMpTaNX0tMM9AudsRLt50QPsZkcAVDiMhsegW+vfAAkM4cw4IvdKqgkv/9JYt+HCAd3pErTzh+MRLxr5HkagfV8aZfeU/fLrXAo9vGpnc/v23tbWoPRh8pWyOJ78gnxsPZHgKRsNNSJ2AYW5ApU="
install:
- cp config/api-common.env config/api.env
- cp config/database-common.env config/database.env
- docker-compose build
- docker-compose up -d
script:
- echo `bash <(curl -s https://codecov.io/env)`
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api
  && make migration"
- docker-compose exec -e CODECOV_ENV=$CODECOV_ENV -e CODECOV_TOKEN=$CODECOV_TOKEN -e CODECOV_URL=$CODECOV_URL -e CODECOV_SLUG=$CODECOV_SLUG -e VCS_COMMIT_ID=$VCS_COMMIT_ID -e VCS_BRANCH_NAME=$VCS_BRANCH_NAME -e VCS_PULL_REQUEST=$VCS_PULL_REQUEST -e VCS_SLUG=$VCS_SLUG -e VCS_TAG=$VCS_TAG -e CI_BUILD_URL=$CI_BUILD_URL -e CI_BUILD_ID=$CI_BUILD_ID -e CI_JOB_ID=$CI_JOB_ID -e CI=$CI -e TRAVIS=$TRAVIS -e SHIPPABLE=$SHIPPABLE -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e TRAVIS_COMMIT=$TRAVIS_COMMIT -e TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG -e TRAVIS_TAG=$TRAVIS_TAG -e TRAVIS_OS_NAME=$TRAVIS_OS_NAME api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && ../go.test.sh"
after_success:
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/melvin-laplanche/ml-api/src
  && head coverage.txt && include_cov=coverage.txt bash <(curl -s https://codecov.io/bash)"
deploy:
  - provider: script
    on: staging
    skip_cleanup: true
    script: ./deploy_staging.sh
notifications:
  email:
    recipients:
      secure: "fjpT9Utz25ML9Z6ShtwSm3rn8aRBh7TiMEAFplTGqMJAglWb05tPrUA0186nim4K1fNUgVedVEqnhPF/htZsq88T3d1Hq3Fm9xI4vpA53O/p8mZTOr2iweqKei+YSsxddNTYs/+EoYTNViuRR3sb/M/BhWOlAwIgqeiLo8kNpe0="
    on_success: change
    on_failure: always
