version: '2'
services:
  api:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/go/src/github.com/melvin-laplanche/ml-api
    depends_on:
      - database
    env_file:
      - ./config/api-common.env
      - ./config/database-common.env
      - ./config/api-${ML_BUILD_ENV}.env
    container_name: ml_api

  database:
    image: postgres:9.6
    ports:
      - "5432:5432"
    env_file:
      - ./config/database-common.env
    container_name: ml_api_postgres