## Featured user [/users/featured]

### Get the featured user [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Attributes (User)

+ Response 404 (application/json)

    The resoure does not exist

    + Attributes (Error404)

+ Response 500 (application/json)

    The server experenced an internal error.

    + Attributes (Error500)
