## User

+ id (required, string)
+ name (required, string)
+ first_name (required, string)
+ last_name (required, string)
+ email (string)
+ is_admin (boolean)
+ picture (string)
+ public_email (string)
+ phone_number (string)
+ linkedin_custom_url (string)
+ facebook_username (string)
+ twitter_username (string)

## Users

+ results (array[User])