### Search an article [GET]

+ Request (application/json)
    + Attributes (Pagination)
        + q (string) - Query to search in content and title
        + order (string) - List of field to order the results separated by a pipe (|)
            Allowed values are: created_at, published_at
            Use a dash (-) to inverse the ordering
        + status: published (string) - List of allowed status separated by a pipe (|)
            Allowed values are: created_at, published_at

+ Response 201 (application/json)

    The session has been created

    + Attributes (Articles)


+ Response 400 (application/json)

    A value is missing or contains the wrong data.

    + Body

            {
                "error": "[reason]"
            }

+ Response 500 (application/json)

    The server experenced an internal error.

    + Body

            {
                "error": "something went wrong"
            }