### Create an article [POST]

+ Request (application/json)
    + Attributes
        + title (required, string) - Title of the article
        + subtitle (string) - subtitle of the article
        + description (string) - Description of the article
        + content (string) - Body of the article

+ Response 201 (application/json)

    The article has been created

    + Attributes (Article)


+ Response 400 (application/json)

    A value is missing or contains the wrong data.

    + Body

            {
                "error": "[reason]"
            }

+ Response 403 (application/json)

    The requester does not have the permission to access this resource.

    + Body

            {
                "error": "Unauthorized"
            }

+ Response 409 (application/json)

    The slug is already in use.

    + Body

            {
                "error": "[reason]"
            }

+ Response 500 (application/json)

    The server experenced an internal error.

    + Body

            {
                "error": "something went wrong"
            }