### Update an article [PATCH]

This endpoint is only accessible through an admin account.

+ Request (application/json)

    + Headers

            Authorization: basic [base64encoded userID:access_token]

    + Attributes
        + slug (string) - New slug for the article
        + version (string) - ID of the new version to use.
        + publish (boolean) - New status of the article

+ Response 200 (application/json)

    The articles has been updated

    + Attributes (Article)

+ Response 400 (application/json)

    A value is missing or contains the wrong data.

    + Body

            {
                "error": "[reason]"
            }

+ Response 403 (application/json)

    The requester does not have the permission to access this resource.

    + Body

            {
                "error": "Unauthorized"
            }

+ Response 404 (application/json)

    The article or the ID provided as version does not exist.

    + Body

            {
                "error": "Not Found"
            }

+ Response 500 (application/json)

    The server experenced an internal error.

    + Body

            {
                "error": "something went wrong"
            }