### Get an article [GET]

+ Request (application/json)

    + Body

+ Response 200 (application/json)

    + Attributes (Article)

+ Response 400 (application/json)

    A value is missing or contains the wrong data.

    + Body

            {
                "error": "[reason]"
            }

+ Response 404 (application/json)

    The article does not exist or the requester doesn't have access to it

    + Body

            {
                "error": "Unauthorized"
            }

+ Response 500 (application/json)

    The server experenced an internal error.

    + Body

            {
                "error": "something went wrong"
            }