FORMAT: 1A
HOST: http://api-orchid.melvin.la/

# api.melvin.la

API used to run melvin.la

:[Group User](../src/components/users/users.apib)

:[Group Session](../src/components/sessions/sessions.apib)

# Data Structure

## User

+ id (required, string)
+ name (required, string)
+ email (string)
+ is_admin (boolean)

## Session

+ token (required, string)
+ user_id (required, string)

## Pagination

+ page: 1 (number) - Page to get
+ per_page (number) - Number of element to get