FORMAT: 1A
HOST: http://api-orchid.melvin.la/

# api.melvin.la

API used to run melvin.la

:[Group User](../src/components/users/users.apib)

:[Group Session](../src/components/sessions/sessions.apib)

:[Group About](../src/components/about/about.apib)

# Data Structure

## User

+ id (required, string)
+ name (required, string)
+ email (string)
+ is_admin (boolean)

## Session

+ token (required, string)
+ user_id (required, string)

## Organization

+ id (required, string)
+ created_at (string)
+ updated_at (string)
+ deleted_at (string)
+ name (required, string)
+ short_name (string)
+ website (string)
+ logo (string)

## Organizations

+ results (array[Organization])

## Experience

+ id (required, string)
+ created_at (string)
+ updated_at (string)
+ deleted_at (string)
+ job_title (required, string)
+ location (string)
+ description (string)
+ start_date (required, string)
+ end_date (string)
+ organization (required, Organization)

## ListExperience

+ results (array[Experience])

## Education

+ id (required, string)
+ created_at (string)
+ updated_at (string)
+ deleted_at (string)
+ degree (required, string)
+ gpa (string)
+ location (string)
+ description (string)
+ start_year (required, number)
+ end_year (number)
+ organization (required, Organization)

## ListEducation

+ results (array[Experience])

## DefaultError

+ error : not a valid uuid (required, string) - Reason of the error
+ field : id (string) - Name of the field that failed

## Error401

+ error : unauthorized (required, string)

## Error403

+ error : forbiden (required, string)

## Error404

+ error : not found (required, string)

## Error500

+ error : something went wrong (required, string)
