FORMAT: 1A
HOST: http://api-orchid.melvin.la/

# api.melvin.la

API used to run melvin.la

:[Group User](user/main.apib)

:[Group Session](session/main.apib)

:[Group Session](blog/main.apib)

# Data Structure

## User

+ id (required, string)
+ name (required, string)
+ email (string)
+ is_admin (boolean)

## Session

+ token (required, string)
+ user_id (required, string)

## Article

+ id (required, string)
+ slug (required, string)
+ title (required, string)
+ content (required, string)
+ subtitle (required, string)
+ description (required, string)
+ create_at (required, string)
+ updated_at (string) - UTC date with the ISO8601 format
+ published_at (string) - UTC date with the ISO8601 format
+ user (required, User) - Author of the article

## Articles

+ Results (required, array[Article])

## Pagination

+ page: 1 (number) - Page to get
+ per_page (number) - Number of element to get