# Group Users

## User [/users/{id}]

+ Parameters
    + id (string) - ID of the targeted user

:[Item Get](item_get.apib)

:[Item Patch](item_patch.apib)

:[Item Delete](item_delete.apib)

## User Collection [/users]

:[Col Post](col_post.apib)
