### Create an Education [POST]

+ Request (application/json)

    + Headers

            Authorization: basic [base64encoded userID:access_token]

    + Attributes
        + organization_id (required, string) - ID of the organization the experience is for
        + degree (required, string) - Name of the degree
        + gpa (string) - GPA
        + location (required, string) - Location
        + description (required, string) - Description of the work accomplished
        + start_year (required, number) - Year started.
        + end_year (number) - Year ended

+ Response 201 (application/json)

    The ressource has been created

    + Attributes (Education)


+ Response 400 (application/json)

    A value is missing or contains the wrong data.

    + Attributes (DefaultError)

+ Response 401 (application/json)

    The requester is not logged in

     + Attributes (Error401)

+ Response 403 (application/json)

    The requester does not have the permission to update this resource

     + Attributes (Error403)

+ Response 404 (application/json)

    The ressource does not exist

    + Attributes (Error404)

+ Response 409 (application/json)

    A value already exists in the database.

    + Attributes (DefaultError)

+ Response 500 (application/json)

    The server experenced an internal error.

    + Attributes (Error500)