## Education [/about/education/{id}]

+ Parameters
    + id (string) - ID of the targeted education

:[Get](get.handler.apib)
:[Update](update.handler.apib)
:[Delete](delete.handler.apib)

## Education Collection [/about/education{?page,per_page,deleted,orphans}]

:[Add](add.handler.apib)
:[List](list.handler.apib)