## Education

+ id (required, string)
+ created_at (string)
+ updated_at (string)
+ deleted_at (string)
+ degree (required, string)
+ gpa (string)
+ location (string)
+ description (string)
+ start_year (required, number)
+ end_year (number)
+ organization (required, Organization)

## ListEducation

+ results (array[Experience])