## Organization

+ id (required, string)
+ created_at (string)
+ updated_at (string)
+ deleted_at (string)
+ name (required, string)
+ short_name (string)
+ website (string)
+ logo (string)

## Organizations

+ results (array[Organization])