## Organization [/about/organizations/{id}]

+ Parameters
    + id (string) - ID of the targeted organization

:[Delete](delete.handler.apib)
:[Update](update.handler.apib)

## Organization Logo [/about/organizations/{id}/logo]

+ Parameters
    + id (string) - ID of the targeted organization

:[Update Logo](upload_logo.handler.apib)

## Organization Collection [/about/organizations]

:[Add](add.handler.apib)
