### Update a Logo [PUT]

+ Request (multipart/form-data; boundary=---BOUNDARY)

    + Headers

            Authorization: basic [base64encoded userID:access_token]

    + Body

            -----BOUNDARY
            Content-Disposition: form-data; name="logo"; filename="logo.png"
            Content-Type: image/png

            data
            -----BOUNDARY

+ Response 200 (application/json)

    The logo has been uploaded

    + Attributes (Organization)


+ Response 400 (application/json)

    Invalid file format

    + Body

            {
                "error": "[reason]",
                "field": "[name of the field that failed]"
            }

+ Response 401 (application/json)

    The user is not logged in

    + Body

            {
                "error": "Unauthorized"
            }

+ Response 403 (application/json)

    The requester does not have the permission to update this resource

    + Body

            {
                "error": "Forbidden"
            }

+ Response 500 (application/json)

    The server experenced an internal error.

    + Body

            {
                "error": "something went wrong"
            }